### ISSUE TITLE
Unable to start the GUI - file 'display.launch' was not found

### ISSUE THREAD

**Issue by matoha** [HarvestX/MG400_ROS2#200]
Hi,

I'm a new ROS user and just got the MG400 arm - thank you so much for creating the open-source ROS2 drivers for the MG400!

After running the installation following the README.md (which all proceeds successfully), I'm unable to start the GUI:

```
ubuntu@a:~$ source ~/ws_ros2/install/setup.bash
ubuntu@a:~$ ros2 launch mg400_bringup display.launch
file 'display.launch' was not found in the share directory of package 'mg400_bringup' which is at '/home/ubuntu/ws_ros2/install/mg400_bringup/share/mg400_bringup'
```

Yet the launch files do exist:
```
ubuntu@a:~$ ls /home/ubuntu/ws_ros2/install/mg400_bringup/share/mg400_bringup
hook  launch  package.bash  package.dsv  package.ps1  package.sh  package.xml  package.zsh  rviz
ubuntu@a~$ ls /home/ubuntu/ws_ros2/install/mg400_bringup/share/mg400_bringup/launch/
display.launch.py  joy.launch.py  main.launch.py  mg400.launch.py
```

What am I doing wrong, please? I'm using Humble Hawksbill & Ubuntu 22.04 - which should be supported.

Thanks
Martin

**Comment by m12watanabe1a** [comment]
Sorry, this is because of the typo of our document.
Please check out the updated readme and I think you could launch GUI with the following command.

```bash
ros2 launch mg400_bringup display.launch.py
```

Thank you so much telling us that.

**Comment by matoha** [comment]
Great, thanks for the explanation & fix!
