### ISSUE TITLE
I can't build package because lack of h6x_tf_handler, p9n_interface

### ISSUE THREAD

**Issue by Thanappu** [HarvestX/MG400_ROS2#209]
I'm new for ROS2 systems and try Dobot MG400 with ROS2
I'm create Workspace and clone your git on my src folder and try to colcon build in my ws.
and it can't build i try to check by rosdep install -i --from-path src 
and founded i lack h6x_tf_handler, p9n_interface 
So i try command sudo apt install ros-humble-p9n_interface but It's not found 
How should i do, Thank

**Comment by Thanappu** [comment]
Now I git clone PlayStation-JoyInterface-ROS2 and try to build It's Okay but lack of  h6x_tf_handler I try https://github.com/HarvestX/h6x_tf_manager   but It's not solution

**Comment by Thanappu** [comment]
Okay i try to build with this command colcon build --symlink-install and every thing is pass.

**Comment by Mt-is-at-O** [comment]
I fixed it with this PR above so h6x_tf_handler is no longer needed. And you should be able to bulid without --symlink-install tag.
