### ISSUE TITLE
joy.launch.py how-to

### ISSUE THREAD

**Issue by hanschanhs** [HarvestX/MG400_ROS2#210]
I have the dobot connected to my computer, which has all the packages installed, and a nintendo/xbox controller is connected to the computer.
The controller is detected and I can use the R1 key to change the jog mode

[component_container-1] [INFO] [1689152321.953695958] [mg400.joy]: Opened joystick: Nintendo Switch Pro Controller.  deadzone: 0.050000
[component_container-1] [INFO] [1689152333.580419247] [mg400.mg400_joy_interface_node]: JogMode: Linear
[component_container-1] [INFO] [1689152335.523595406] [mg400.mg400_joy_interface_node]: JogMode: Joint

but when I actually move the joysticks I get the error
[component_container-1] [ERROR] [1689152341.060421895] [mg400.mg400_joy_interface_node]: "/mg400/move_jog" is not ready
[component_container-1] [ERROR] [1689152342.060994892] [mg400.mg400_joy_interface_node]: "/mg400/move_jog" is not ready
[component_container-1] [ERROR] [1689152349.169265270] [mg400.mg400_joy_interface_node]: "/mg400/move_jog" is not ready

Should I launch :
`ros2 launch mg400_bringup main.launch.py` 
on a different terminal before launching
`ros2 launch mg400_bringup joy.launch.py` ?

Also is it possible to use joy.launch.py to control the simulated robotic arm in rviz? As this will be very useful for me.
If yes, how?

Really appreciate help as new to ROS.

**Comment by kobayashi-na** [comment]
> Should I launch :
> ros2 launch mg400_bringup main.launch.py
> on a different terminal before launching
> ros2 launch mg400_bringup joy.launch.py ?

Partially yes:
You should both launch `main.launch.py` and `joy.launch.py` on a different terminal, but either order is fine.
In your case,  `"/mg400/move_jog" is not ready` error is due to a lack of mg400 service server, witch is created by `main.launch.py`.

> Also is it possible to use joy.launch.py to control the simulated robotic arm in rviz?

Yes:
Please use [MG400_Mock](https://github.com/HarvestX/MG400_Mock).
